// apps/www/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { Fragment, useState } from "react";

import LiveTime from "../components/live-time.tsx";
import PushButton from "../components/push-button.tsx";
import SocialSticker from "../components/social-sticker.tsx";
import { projects, socials, workHistory } from "../lib/data.ts";

const tickerWords = [
  "curious",
  "tinkerer",
  "builds for fun",
  "open source",
  "probably debugging",
  "say hi",
  "always learning",
  "breaks things to fix them",
  "loves a good refactor",
  "ships it",
  "reads the source",
  "automates the boring",
  "late night commits",
  "breaking things",
  "shipping on fridays",
  "fixing other people's problems",
];

const stickerTilts = [
  "-rotate-2",
  "rotate-1",
  "rotate-2",
  "-rotate-1",
  "rotate-3",
  "-rotate-3",
  "rotate-1",
  "-rotate-2",
];

const stickerInks = [
  "border-violet text-violet hover:bg-violet hover:shadow-[4px_4px_0_var(--color-orange)]",
  "border-orange-deep text-orange-deep hover:bg-orange-deep hover:shadow-[4px_4px_0_var(--color-violet)]",
  "border-ink text-ink hover:bg-ink hover:shadow-[4px_4px_0_var(--color-orange)]",
];

export const Route = createFileRoute("/")({
  component: HomePage,
});

function HomePage() {
  const age = new Date().getFullYear() - 2005;

  const [openModal, setOpenModal] = useState<string | null>(null);

  return (
    <>
      <main className="mx-auto max-w-4xl px-5 pb-16 sm:px-8">
        <header className="animate-reveal border-violet/35 text-violet flex flex-wrap items-center justify-between gap-2 border-b-2 border-dashed py-4 text-xs font-bold tracking-[0.18em] uppercase motion-reduce:animate-none">
          <span>blankparticle.com</span>
          <span className="text-orange-deep hidden sm:inline">est. 2005 · 100% handmade</span>
          <span>
            my time: <LiveTime /> ist
          </span>
        </header>

        <section className="flex flex-col gap-10 py-12 sm:py-16 md:flex-row md:items-center md:justify-between">
          <div className="flex max-w-xl flex-col gap-5">
            <p className="animate-reveal text-ink-muted text-lg font-bold tracking-wide [animation-delay:90ms] motion-reduce:animate-none">
              Hello, I'm
            </p>
            <h1 className="animate-reveal font-display text-violet text-[clamp(3.5rem,9vw,6.5rem)] leading-[0.95] font-extrabold tracking-tight [animation-delay:180ms] motion-reduce:animate-none">
              Rahul Mishra
            </h1>
            <p className="animate-reveal text-ink-muted text-base [animation-delay:270ms] motion-reduce:animate-none">
              also known as
              <a
                href="/gh"
                className="text-ink before:bg-lime relative mx-1 inline-block font-bold before:absolute before:inset-x-[-3px] before:inset-y-[1px] before:-z-10 before:-rotate-1 hover:before:rotate-1"
              >
                @blankparticle
              </a>
              online. {age} years old, software developer at{" "}
              <a
                href="https://iterate.com"
                className="text-orange-deep decoration-orange font-bold underline decoration-wavy decoration-2 underline-offset-4"
                target="_blank"
                rel="noopener noreferrer"
              >
                Iterate
              </a>
              , and forever taking software apart to see how it works.
            </p>
            <div className="animate-reveal flex flex-wrap items-center gap-4 pt-2 [animation-delay:360ms] motion-reduce:animate-none">
              <PushButton variant="violet" onClick={() => setOpenModal("Email")}>
                email me
              </PushButton>
              <PushButton href="/cal" variant="orange">
                book a call
              </PushButton>
              <PushButton href="/resume" variant="violet-outline" target="_blank" rel="noopener noreferrer">
                my resume
              </PushButton>
            </div>
          </div>

          <figure className="animate-reveal relative order-first shrink-0 self-center [animation-delay:270ms] motion-reduce:animate-none md:order-none md:self-auto">
            <span
              className="text-orange absolute -top-6 -right-6 size-28 rounded-full bg-[radial-gradient(currentColor_1px,transparent_1.5px)] bg-size-[9px_9px]"
              aria-hidden="true"
            ></span>
            <span
              className="text-violet absolute -bottom-5 -left-7 size-20 rounded-full bg-[radial-gradient(currentColor_1px,transparent_1.5px)] bg-size-[9px_9px]"
              aria-hidden="true"
            ></span>
            <img
              src="/me.png"
              alt="Rahul, cut out and stuck on the page like a sticker"
              className="border-paper relative size-40 rotate-2 rounded-2xl border-4 object-cover shadow-[0_0_0_2px_var(--color-ink)] transition-transform duration-300 ease-out select-none hover:rotate-0 sm:size-48"
            />
            <figcaption className="border-ink bg-lime absolute -bottom-3 left-1/2 w-max -translate-x-1/2 -rotate-2 border-2 px-2 py-0.5 text-xs font-bold tracking-widest uppercase">
              that's me
            </figcaption>
          </figure>
        </section>

        <div
          className="animate-reveal border-ink bg-violet mx-[calc(50%-50vw)] overflow-hidden border-y-2 py-2 [animation-delay:450ms] motion-reduce:animate-none"
          aria-hidden="true"
        >
          <div className="animate-marquee flex w-max motion-reduce:animate-none">
            {[0, 1, 2, 3, 4, 5].map((half) => (
              <span
                key={half}
                className="text-paper flex shrink-0 items-center text-sm font-extrabold tracking-[0.2em] whitespace-nowrap uppercase"
              >
                {tickerWords.map((word) => (
                  <Fragment key={word}>
                    <span className="px-3">{word}</span>
                    <span>★</span>
                  </Fragment>
                ))}
              </span>
            ))}
          </div>
        </div>

        <section className="animate-reveal flex flex-col gap-2 py-12 [animation-delay:540ms] motion-reduce:animate-none sm:py-16">
          <div className="flex items-baseline justify-between gap-4 pb-4">
            <h2 className="font-display text-violet text-3xl font-extrabold tracking-tight sm:text-4xl">
              Where I've worked
            </h2>
            <span className="text-orange-deep text-xs font-bold tracking-[0.18em] uppercase">the paper trail</span>
          </div>
          <ol className="flex flex-col">
            {workHistory.map((work) => (
              <li key={work.company} className="border-violet/35 border-t-2 border-dashed last:border-b-2">
                <details className="group">
                  <summary className="flex cursor-pointer list-none items-center gap-4 py-5 sm:gap-6 [&::-webkit-details-marker]:hidden">
                    <span
                      className="text-orange-deep shrink-0 text-lg font-bold transition-transform duration-200 ease-out group-open:rotate-90"
                      aria-hidden="true"
                    >
                      →
                    </span>
                    <img
                      src={work.logo}
                      alt={`${work.company} logo`}
                      loading="lazy"
                      className="border-ink bg-ink size-10 shrink-0 -rotate-2 rounded-md border-2 object-cover shadow-[2px_2px_0_var(--color-violet)]"
                    />
                    <span className="flex min-w-0 flex-1 flex-col gap-1">
                      <span className="flex flex-wrap items-baseline gap-x-2 gap-y-1">
                        <a
                          href={work.url}
                          className="font-display text-violet-deep decoration-orange text-xl font-bold decoration-wavy underline-offset-4 hover:underline"
                          target="_blank"
                          rel="noopener noreferrer"
                          onClick={(e) => e.stopPropagation()}
                        >
                          {work.company}
                        </a>
                        {work.companySubtext && (
                          <span className="text-ink-muted/70 text-xs">{work.companySubtext}</span>
                        )}
                      </span>
                      <span className="text-ink-muted text-sm">
                        {work.role} · {work.tags.join(" · ")}
                      </span>
                    </span>
                    <span className="font-display text-orange-deep ml-auto shrink-0 text-sm font-bold tabular-nums">
                      {work.date}
                    </span>
                  </summary>
                  <ul className="flex flex-col gap-2 pb-5 pl-10 sm:pl-12">
                    {work.points.map((point) => (
                      <li key={point} className="text-ink-muted flex gap-2 text-sm">
                        <span className="text-orange-deep shrink-0 font-bold" aria-hidden="true">
                          →
                        </span>
                        <span>{point}</span>
                      </li>
                    ))}
                  </ul>
                </details>
              </li>
            ))}
          </ol>
        </section>

        <section className="animate-reveal flex flex-col gap-2 pb-12 [animation-delay:585ms] motion-reduce:animate-none sm:pb-16">
          <div className="flex items-baseline justify-between gap-4 pb-4">
            <h2 className="font-display text-violet text-3xl font-extrabold tracking-tight sm:text-4xl">
              Things I built
            </h2>
            <span className="text-orange-deep text-xs font-bold tracking-[0.18em] uppercase">hot off the press</span>
          </div>
          <ol className="flex flex-col">
            {projects.map((project, i) => (
              <li key={project.title} className="border-violet/35 border-t-2 border-dashed last:border-b-2">
                <a
                  className="group flex items-baseline gap-4 py-5 sm:gap-6"
                  href={project.url}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <span className="font-display text-orange-deep text-xl font-bold tabular-nums" aria-hidden="true">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <span className="flex min-w-0 flex-col gap-1">
                    <span className="font-display text-violet-deep group-hover:decoration-orange text-xl font-bold break-words underline decoration-transparent decoration-2 underline-offset-4 transition-colors duration-200">
                      {project.title}
                    </span>
                    <span className="text-ink-muted text-sm">{project.description}</span>
                  </span>
                  <span
                    className="text-orange-deep ml-auto shrink-0 text-lg font-bold transition-transform duration-200 ease-out group-hover:translate-x-1"
                    aria-hidden="true"
                  >
                    →
                  </span>
                </a>
              </li>
            ))}
          </ol>
        </section>

        <section className="animate-reveal flex flex-col gap-6 pb-14 [animation-delay:630ms] motion-reduce:animate-none">
          <div className="flex items-baseline justify-between gap-4">
            <h2 className="font-display text-violet text-3xl font-extrabold tracking-tight sm:text-4xl">
              Find me around
            </h2>
            <span className="text-orange-deep text-xs font-bold tracking-[0.18em] uppercase">socials sheet</span>
          </div>
          <div className="flex flex-wrap gap-x-3 gap-y-4">
            {socials
              .filter((x) => x.showAsSticker !== false)
              .map((social, i) => {
                const tilt = stickerTilts[i % stickerTilts.length];
                const ink = stickerInks[i % stickerInks.length];
                return (
                  <SocialSticker
                    key={social.label}
                    name={social.label}
                    tilt={tilt}
                    ink={ink}
                    {...(social.modal ? { onClick: () => setOpenModal(social.label) } : { href: social.shortLink[0] })}
                  />
                );
              })}
          </div>
        </section>

        <footer className="animate-reveal border-violet/35 flex flex-col items-center gap-4 border-t-2 border-dashed pt-6 text-center text-xs font-bold [animation-delay:720ms] motion-reduce:animate-none sm:flex-row sm:flex-wrap sm:justify-between sm:text-left">
          <a
            href="/gh/BlankParticle"
            className="text-violet decoration-orange underline decoration-wavy underline-offset-4"
            target="_blank"
            rel="noopener noreferrer"
          >
            Made with 💜 by BlankParticle
          </a>
          <span className="border-orange-deep text-orange-deep order-last -rotate-2 rounded border-2 border-dashed px-2 py-1 tracking-[0.18em] uppercase sm:order-none">
            printed on the internet
          </span>
          <a
            href="https://tanstack.com/start"
            className="text-violet decoration-orange underline decoration-wavy underline-offset-4"
            target="_blank"
            rel="noopener noreferrer"
          >
            🌀 Powered by TanStack Start
          </a>
        </footer>
      </main>

      {socials.map(
        (social) =>
          social.modal && (
            <social.modal key={social.label} open={openModal === social.label} onClose={() => setOpenModal(null)} />
          ),
      )}
    </>
  );
}

// src/routes/+page.svelte
<script lang="ts">
  import type { PageData } from "./$types";
  import Confirm from "../icons/confirm.svelte";
  import LiveTime from "../components/live-time.svelte";
  import PushButton from "../components/push-button.svelte";
  import SocialSticker from "../components/social-sticker.svelte";
  import ContactDialog from "../components/contact-dialog.svelte";
  import { copyText } from "../lib/clipboard";
  import { socials } from "../lib/socials";

  const DOMAIN = "blankparticle.com";
  const email = `hello@${DOMAIN}`;
  const discordUser = "blankparticle";

  let { data }: { data: PageData } = $props();
  const age = new Date().getFullYear() - 2005;

  let emailCopied = $state(false);
  let emailOpen = $state(false);
  let discordOpen = $state(false);

  const tickerWords = [
    "curious",
    "tinkerer",
    "builds for fun",
    "open source",
    "probably debugging",
    "say hi",
    "always learning",
    "breaks things to fix them",
    "loves a good refactor",
    "ships it",
    "reads the source",
    "automates the boring",
    "late night commits",
    "breaking things",
    "shipping on fridays",
    "fixing other people's problems",
  ];
  const stickerTilts = [
    "-rotate-2",
    "rotate-1",
    "rotate-2",
    "-rotate-1",
    "rotate-3",
    "-rotate-3",
    "rotate-1",
    "-rotate-2",
  ];
  const stickerInks = [
    "border-violet text-violet hover:bg-violet hover:shadow-[4px_4px_0_var(--color-orange)]",
    "border-orange-deep text-orange-deep hover:bg-orange-deep hover:shadow-[4px_4px_0_var(--color-violet)]",
    "border-ink text-ink hover:bg-ink hover:shadow-[4px_4px_0_var(--color-orange)]",
  ];
</script>

<main class="mx-auto max-w-4xl px-5 pb-16 sm:px-8">
  <header
    class="flex animate-reveal flex-wrap items-center justify-between gap-2 border-b-2 border-dashed border-violet/35 py-4 text-xs font-bold tracking-[0.18em] text-violet uppercase motion-reduce:animate-none"
  >
    <span>{DOMAIN}</span>
    <span class="hidden text-orange-deep sm:inline">est. 2005 · 100% handmade</span>
    <span>my time: <LiveTime /> ist</span>
  </header>

  <section class="flex flex-col gap-10 py-12 sm:py-16 md:flex-row md:items-center md:justify-between">
    <div class="flex max-w-xl flex-col gap-5">
      <p
        class="animate-reveal text-lg font-bold tracking-wide text-ink-muted [animation-delay:90ms] motion-reduce:animate-none"
      >
        Hello, I'm
      </p>
      <h1
        class="animate-reveal font-display text-[clamp(3.5rem,9vw,6.5rem)] leading-[0.95] font-extrabold tracking-tight text-violet [animation-delay:180ms] motion-reduce:animate-none"
      >
        Rahul Mishra
      </h1>
      <p class="animate-reveal text-base text-ink-muted [animation-delay:270ms] motion-reduce:animate-none">
        also known as
        <a
          href="/gh"
          class="relative mx-1 inline-block font-bold text-ink before:absolute before:inset-x-[-3px] before:inset-y-[1px] before:-z-10 before:-rotate-1 before:bg-lime hover:before:rotate-1"
          >@blankparticle</a
        >
        online. {age} years old, software developer at
        <a
          href="https://iterate.com"
          class="font-bold text-orange-deep underline decoration-orange decoration-wavy decoration-2 underline-offset-4"
          target="_blank"
          rel="noopener noreferrer">Iterate</a
        >, and forever taking software apart to see how it works.
      </p>
      <div
        class="flex animate-reveal flex-wrap items-center gap-4 pt-2 [animation-delay:360ms] motion-reduce:animate-none"
      >
        <PushButton
          variant="violet"
          aria-live="polite"
          aria-atomic="true"
          onclick={() => copyText(email, (v) => (emailCopied = v))}
        >
          {#if emailCopied}
            <Confirm />
          {:else}
            email me
          {/if}
        </PushButton>
        <PushButton href="/cal" variant="orange">book a call</PushButton>
        <PushButton href="/resume" variant="violet-outline" target="_blank" rel="noopener noreferrer">
          my resume
        </PushButton>
      </div>
    </div>

    <figure
      class="order-first shrink-0 animate-reveal relative self-center [animation-delay:270ms] motion-reduce:animate-none md:order-none md:self-auto"
    >
      <span
        class="absolute -top-6 -right-6 size-28 rounded-full bg-[radial-gradient(currentColor_1px,transparent_1.5px)] bg-size-[9px_9px] text-orange"
        aria-hidden="true"
      ></span>
      <span
        class="absolute -bottom-5 -left-7 size-20 rounded-full bg-[radial-gradient(currentColor_1px,transparent_1.5px)] bg-size-[9px_9px] text-violet"
        aria-hidden="true"
      ></span>
      <img
        src="/me.png"
        alt="Rahul, cut out and stuck on the page like a sticker"
        class="relative size-40 rotate-2 rounded-2xl border-4 border-paper object-cover shadow-[0_0_0_2px_var(--color-ink)] transition-transform duration-300 ease-out select-none hover:rotate-0 sm:size-48"
      />
      <figcaption
        class="absolute -bottom-3 left-1/2 w-max -translate-x-1/2 -rotate-2 border-2 border-ink bg-lime px-2 py-0.5 text-xs font-bold tracking-widest uppercase"
      >
        that's me
      </figcaption>
    </figure>
  </section>

  <div
    class="mx-[calc(50%-50vw)] animate-reveal overflow-hidden border-y-2 border-ink bg-violet py-2 [animation-delay:450ms] motion-reduce:animate-none"
    aria-hidden="true"
  >
    <div class="flex w-max animate-marquee motion-reduce:animate-none">
      {#each [0, 1, 2, 3, 4, 5] as half (half)}
        <span
          class="flex shrink-0 items-center text-sm font-extrabold tracking-[0.2em] whitespace-nowrap text-paper uppercase"
        >
          {#each tickerWords as word}
            <span class="px-3">{word}</span>
            <span>★</span>
          {/each}
        </span>
      {/each}
    </div>
  </div>

  <section class="flex animate-reveal flex-col gap-2 py-12 [animation-delay:540ms] motion-reduce:animate-none sm:py-16">
    <div class="flex items-baseline justify-between gap-4 pb-4">
      <h2 class="font-display text-3xl font-extrabold tracking-tight text-violet sm:text-4xl">Where I've worked</h2>
      <span class="text-xs font-bold tracking-[0.18em] text-orange-deep uppercase">the paper trail</span>
    </div>
    <ol class="flex flex-col">
      {#each data.work as job (job.company)}
        <li class="border-t-2 border-dashed border-violet/35 last:border-b-2">
          <details class="group">
            <summary
              class="flex cursor-pointer list-none items-center gap-4 py-5 sm:gap-6 [&::-webkit-details-marker]:hidden"
            >
              <span
                class="shrink-0 text-lg font-bold text-orange-deep transition-transform duration-200 ease-out group-open:rotate-90"
                aria-hidden="true">→</span
              >
              <img
                src={job.logo}
                alt="{job.company} logo"
                loading="lazy"
                class="size-10 shrink-0 -rotate-2 rounded-md border-2 border-ink bg-ink object-cover shadow-[2px_2px_0_var(--color-violet)]"
              />
              <span class="flex min-w-0 flex-1 flex-col gap-1">
                <span class="flex flex-wrap items-baseline gap-x-2 gap-y-1">
                  <a
                    href={job.url}
                    class="font-display text-xl font-bold text-violet-deep decoration-orange decoration-wavy underline-offset-4 hover:underline"
                    target="_blank"
                    rel="noopener noreferrer"
                    onclick={(e) => e.stopPropagation()}>{job.company}</a
                  >
                  {#if job.companySubtext}
                    <span class="text-xs text-ink-muted/70">{job.companySubtext}</span>
                  {/if}
                </span>
                <span class="text-sm text-ink-muted">
                  {job.role} · {job.tags.join(" · ")}
                </span>
              </span>
              <span class="ml-auto shrink-0 font-display text-sm font-bold text-orange-deep tabular-nums">
                {job.date}
              </span>
            </summary>
            <ul class="flex flex-col gap-2 pb-5 pl-10 sm:pl-12">
              {#each job.points as point}
                <li class="flex gap-2 text-sm text-ink-muted">
                  <span class="shrink-0 font-bold text-orange-deep" aria-hidden="true">→</span>
                  <span>{point}</span>
                </li>
              {/each}
            </ul>
          </details>
        </li>
      {/each}
    </ol>
  </section>

  <section class="flex animate-reveal flex-col gap-2 pb-12 [animation-delay:585ms] motion-reduce:animate-none sm:pb-16">
    <div class="flex items-baseline justify-between gap-4 pb-4">
      <h2 class="font-display text-3xl font-extrabold tracking-tight text-violet sm:text-4xl">Things I built</h2>
      <span class="text-xs font-bold tracking-[0.18em] text-orange-deep uppercase">hot off the press</span>
    </div>
    <ol class="flex flex-col">
      {#each data.projects as project, i}
        <li class="border-t-2 border-dashed border-violet/35 last:border-b-2">
          <a
            class="group flex items-baseline gap-4 py-5 sm:gap-6"
            href={project.url}
            target="_blank"
            rel="noopener noreferrer"
          >
            <span class="font-display text-xl font-bold text-orange-deep tabular-nums" aria-hidden="true">
              {String(i + 1).padStart(2, "0")}
            </span>
            <span class="flex min-w-0 flex-col gap-1">
              <span
                class="font-display text-xl font-bold break-words text-violet-deep underline decoration-transparent decoration-2 underline-offset-4 transition-colors duration-200 group-hover:decoration-orange"
              >
                {project.title}
              </span>
              <span class="text-sm text-ink-muted">{project.description}</span>
            </span>
            <span
              class="ml-auto shrink-0 text-lg font-bold text-orange-deep transition-transform duration-200 ease-out group-hover:translate-x-1"
              aria-hidden="true">→</span
            >
          </a>
        </li>
      {/each}
    </ol>
  </section>

  <section class="flex animate-reveal flex-col gap-6 pb-14 [animation-delay:630ms] motion-reduce:animate-none">
    <div class="flex items-baseline justify-between gap-4">
      <h2 class="font-display text-3xl font-extrabold tracking-tight text-violet sm:text-4xl">Find me around</h2>
      <span class="text-xs font-bold tracking-[0.18em] text-orange-deep uppercase">socials sheet</span>
    </div>
    <div class="flex flex-wrap gap-x-3 gap-y-4">
      {#each Object.entries(socials) as [link, name], i (link)}
        {@const tilt = stickerTilts[i % stickerTilts.length]}
        {@const ink = stickerInks[i % stickerInks.length]}
        {#if link === "email"}
          <SocialSticker {name} {tilt} {ink} onclick={() => (emailOpen = true)} />
        {:else if link === "discord"}
          <SocialSticker {name} {tilt} {ink} onclick={() => (discordOpen = true)} />
        {:else}
          <SocialSticker {name} {tilt} {ink} href={`/${link}`} />
        {/if}
      {/each}
    </div>
  </section>

  <footer
    class="flex animate-reveal flex-col items-center gap-4 border-t-2 border-dashed border-violet/35 pt-6 text-center text-xs font-bold [animation-delay:720ms] motion-reduce:animate-none sm:flex-row sm:flex-wrap sm:justify-between sm:text-left"
  >
    <a
      href="/gh/www"
      class="text-violet underline decoration-orange decoration-wavy underline-offset-4"
      target="_blank"
      rel="noopener noreferrer"
    >
      Made with 💜 by BlankParticle
    </a>
    <span
      class="order-last -rotate-2 rounded border-2 border-dashed border-orange-deep px-2 py-1 tracking-[0.18em] text-orange-deep uppercase sm:order-none"
    >
      printed on the internet
    </span>
    <a
      href="https://svelte.dev"
      class="text-violet underline decoration-orange decoration-wavy underline-offset-4"
      target="_blank"
      rel="noopener noreferrer"
    >
      🍀 Powered by SvelteKit
    </a>
  </footer>
</main>

<ContactDialog
  bind:open={emailOpen}
  title="Drop me a line"
  description="Copy my email and reach out whenever you like."
  value={email}
  copyLabel="Copy email"
/>

<ContactDialog
  bind:open={discordOpen}
  title="Let's connect on Discord"
  description="Add me as a friend with my username below."
  value={discordUser}
  copyLabel="Copy Discord username"
  actionHref="/discord"
  actionLabel="Open in Discord"
/>
